[snake_game]
size = 50
winning_reward = 3
eaten_food_reward = 1
early_done_penalty = 2
living_penalty = 0.05

[ppo]
discount_factor = 0.9
gae_factor = 0.95
clip_factor = 0.3
n_epochs = 10
batch_size = 5
buffer_size = 20
n_iter = 0
value_loss_coef = 0.5
entropy_loss_coef = 0.1

[icm]
forward_loss_coef = 0.2
pg_loss_coef = 0.1
eta = 1.0
